In [1]:
import pandas as pd
import re

In [2]:
data = pd.read_csv('city_data.csv', sep = '|', header = 1, index_col = 0)
data

,Population Density,Population,Working Age Population,Youth Dependency Ratio,Unemployment Rate,GDP per Capita,Days of very strong heat stress,Main Spoken Languages,Average Monthly Salary,Avgerage Rent Price,Average Cost of Living,Average Price Groceries,Last Data Update
City,,,,,,,,,,,,,
"Vienna, Austria",310.0,2983513,2018818.0,20.1,10.2,55770.0,3,"German, English, Turkish, Serbian",2500,1050,2061,340.0,2024-06-15 00:00:00
"Salzburg, Austria",243.0,375489,250472.0,20.3,3.0,66689.0,0,German,3200,1100,2186,NaN,2023-11-03 00:00:00
"Brussels, Belgium",681.0,3284548,2137425.0,27.5,10.7,62500.0,3,"French, Dutch, Arabic, English",3350,1200,1900,NaN,2023-04-22 00:00:00
"Antwerp, Belgium",928.0,1139663,723396.0,27.7,6.2,57595.0,3,"Dutch, French, Arabic",2609,900,1953,NaN,2024-08-09 00:00:00
"Gent, Belgium",552.0,645813,417832.0,24.8,NaN,53311.0,2,"Dutch, French",2400,827,1200,120.0,2023-07-17 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Stockholm, Sweden",334.0,2344124,1534225.0,28.5,6.2,70950.0,0,"Swedish, English",2700,1400,2300,NaN,2024-09-11 00:00:00
"Gothenburg, Sweden",245.0,1037675,672152.0,28.2,6.3,49588.0,0,"Swedish, English",2500,1200,2100,NaN,2023-03-10 00:00:00
"Malmo, Sweden",368.0,680335,436271.0,29.4,9.2,44387.0,0,"Swedish, English",2400,1100,2000,NaN,2024-07-07 00:00:00
"Ankara, Turkiye",1922.0,4843511,3417691.0,30.0,14.4,38916.0,3,Turkish,900,450,900,309.0,2023-06-08 00:00:00
"Adana, Turkiye",552.0,1074543,718256.0,37.8,12.2,19945.0,59,Turkish,750,350,800,NaN,2024-05-02 00:00:00

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 84 entries, ('Austria', 'Salzburg') to ('United Kingdom', 'London')
Data columns (total 12 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Population Density               84 non-null     float64
 1   Population                       84 non-null     int64
 2   Working Age Population           84 non-null     float64
 3   Youth Dependency Ratio           84 non-null     float64
 4   Unemployment Rate                84 non-null     float64
 5   GDP per Capita                   84 non-null     float64
 6   Days of very strong heat stress  84 non-null     int64
 7   Main Spoken Languages            84 non-null     object
 8   Average Monthly Salary           84 non-null     int64
 9   Avgerage Rent Price              84 non-null     int64
 10  Average Cost of Living           84 non-null     int64
 11  Last Data Update                 84 non-null     object
dtypes: float64(5), int64(5), object(2)
memory usage: 12.1+ KB

In [37]:
data[['Working Age Population ', 'GDP per Capita']] = data[['Working Age Population ', 'GDP per Capita']].astype('int')

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 84 entries, ('Austria', 'Salzburg') to ('United Kingdom', 'London')
Data columns (total 12 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Population Density               84 non-null     float64
 1   Population                       84 non-null     int64
 2   Working Age Population           84 non-null     int64
 3   Youth Dependency Ratio           84 non-null     float64
 4   Unemployment Rate                84 non-null     float64
 5   GDP per Capita                   84 non-null     int64
 6   Days of very strong heat stress  84 non-null     int64
 7   Main Spoken Languages            84 non-null     object
 8   Average Monthly Salary           84 non-null     int64
 9   Avgerage Rent Price              84 non-null     int64
 10  Average Cost of Living           84 non-null     int64
 11  Last Data Update                 84 non-null     object
dtypes: float64(3), int64(7), object(2)
memory usage: 12.1+ KB

In [3]:
data.isna().sum()

Population Density                  1
Population                          0
Working Age Population              1
Youth Dependency Ratio              0
Unemployment Rate                   1
GDP per Capita                      1
Days of very strong heat stress     0
Main Spoken Languages               1
Average Monthly Salary              0
Avgerage Rent Price                 0
Average Cost of Living              0
Average Price Groceries            80
Last Data Update                    0
dtype: int64

In [4]:
data.drop('Average Price Groceries', axis = 1, inplace = True)
data

,Population Density,Population,Working Age Population,Youth Dependency Ratio,Unemployment Rate,GDP per Capita,Days of very strong heat stress,Main Spoken Languages,Average Monthly Salary,Avgerage Rent Price,Average Cost of Living,Last Data Update
City,,,,,,,,,,,,
"Vienna, Austria",310.0,2983513,2018818.0,20.1,10.2,55770.0,3,"German, English, Turkish, Serbian",2500,1050,2061,2024-06-15 00:00:00
"Salzburg, Austria",243.0,375489,250472.0,20.3,3.0,66689.0,0,German,3200,1100,2186,2023-11-03 00:00:00
"Brussels, Belgium",681.0,3284548,2137425.0,27.5,10.7,62500.0,3,"French, Dutch, Arabic, English",3350,1200,1900,2023-04-22 00:00:00
"Antwerp, Belgium",928.0,1139663,723396.0,27.7,6.2,57595.0,3,"Dutch, French, Arabic",2609,900,1953,2024-08-09 00:00:00
"Gent, Belgium",552.0,645813,417832.0,24.8,NaN,53311.0,2,"Dutch, French",2400,827,1200,2023-07-17 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
"Stockholm, Sweden",334.0,2344124,1534225.0,28.5,6.2,70950.0,0,"Swedish, English",2700,1400,2300,2024-09-11 00:00:00
"Gothenburg, Sweden",245.0,1037675,672152.0,28.2,6.3,49588.0,0,"Swedish, English",2500,1200,2100,2023-03-10 00:00:00
"Malmo, Sweden",368.0,680335,436271.0,29.4,9.2,44387.0,0,"Swedish, English",2400,1100,2000,2024-07-07 00:00:00
"Ankara, Turkiye",1922.0,4843511,3417691.0,30.0,14.4,38916.0,3,Turkish,900,450,900,2023-06-08 00:00:00
"Adana, Turkiye",552.0,1074543,718256.0,37.8,12.2,19945.0,59,Turkish,750,350,800,2024-05-02 00:00:00

In [5]:
data[data['Main Spoken Languages'].isna()]

,Population Density,Population,Working Age Population,Youth Dependency Ratio,Unemployment Rate,GDP per Capita,Days of very strong heat stress,Main Spoken Languages,Average Monthly Salary,Avgerage Rent Price,Average Cost of Living,Last Data Update
City,,,,,,,,,,,,
"Dusseldorf, Germany",1295.0,1554077,NaN,21.4,3.3,71238.0,3,NaN,3200,1100,2050,2024-01-15 00:00:00

In [6]:
data.loc[data.index.str.contains('Germany'), ['Main Spoken Languages']].mode()

  Main Spoken Languages
0                German

In [7]:
data.loc[data.index.str.contains('Germany'), ['Working Age Population ']].mean()

Working Age Population     1840473.0
dtype: float64

In [8]:
data.loc['Dusseldorf, Germany', 'Main Spoken Languages'] = 'German'

In [9]:
data.loc['Dusseldorf, Germany', ['Working Age Population ']] =  data.loc[data.index.str.contains('Germany'), ['Working Age Population ']].mean()

mean = median so we used mean

In [10]:
data.loc[['Dusseldorf, Germany'], ['Working Age Population ','Main Spoken Languages']]

                     Working Age Population  Main Spoken Languages
City
Dusseldorf, Germany                1840473.0                German

In [11]:
data.isna().sum()

Population Density                 1
Population                         0
Working Age Population             0
Youth Dependency Ratio             0
Unemployment Rate                  1
GDP per Capita                     1
Days of very strong heat stress    0
Main Spoken Languages              0
Average Monthly Salary             0
Avgerage Rent Price                0
Average Cost of Living             0
Last Data Update                   0
dtype: int64

In [12]:
#now numerical data

In [13]:
data.columns

Index(['Population Density', 'Population', 'Working Age Population ',
       'Youth Dependency Ratio', 'Unemployment Rate', 'GDP per Capita',
       'Days of very strong heat stress', 'Main Spoken Languages',
       'Average Monthly Salary', 'Avgerage Rent Price',
       'Average Cost of Living', 'Last Data Update'],
      dtype='object')

In [14]:
data[data['Population Density'].isna()]

,Population Density,Population,Working Age Population,Youth Dependency Ratio,Unemployment Rate,GDP per Capita,Days of very strong heat stress,Main Spoken Languages,Average Monthly Salary,Avgerage Rent Price,Average Cost of Living,Last Data Update
City,,,,,,,,,,,,
"Valencia, Spain",NaN,1748142,1162828.0,22.6,13.7,33570.0,5,Spanish;Valencian,2400,1190,1300,2023-06-04 00:00:00

In [15]:
data.loc[data.index.str.contains('Spain')]

,Population Density,Population,Working Age Population,Youth Dependency Ratio,Unemployment Rate,GDP per Capita,Days of very strong heat stress,Main Spoken Languages,Average Monthly Salary,Avgerage Rent Price,Average Cost of Living,Last Data Update
City,,,,,,,,,,,,
"Madrid, Spain",873.0,6882461,4617753.0,23.0,10.8,51020.0,18,Spanish,2271,1100,1589,2023-05-14 00:00:00
"Barcelona, Spain",1918.0,5034925,3331345.0,22.6,11.0,45016.0,0,"Spanish, Catalan",2094,1450,1630,2024-10-18 00:00:00
"Valencia, Spain",NaN,1748142,1162828.0,22.6,13.7,33570.0,5,Spanish;Valencian,2400,1190,1300,2023-06-04 00:00:00
"Seville, Spain",330.0,1549641,1037225.0,25.0,21.6,30004.0,53,Spanish,2300,650,1150,2024-09-01 00:00:00
"Malaga, Spain",571.0,869096,585608.0,23.5,17.7,27694.0,0,"Spanish, English",2200,1312,1400,2023-11-27 00:00:00
"Malaga, Spain",571.0,869096,585608.0,23.5,17.7,27694.0,0,"Spanish, English",2200,1312,1400,2023-11-27 00:00:00

In [16]:
data.loc[data.index.str.contains('Spain'), ['Population Density']].median()

Population Density    571.0
dtype: float64

In [17]:
data.loc['Valencia, Spain', ['Population Density']] =  data.loc[data.index.str.contains('Spain'), ['Population Density']].median()

In [18]:
data.isna().sum()

Population Density                 0
Population                         0
Working Age Population             0
Youth Dependency Ratio             0
Unemployment Rate                  1
GDP per Capita                     1
Days of very strong heat stress    0
Main Spoken Languages              0
Average Monthly Salary             0
Avgerage Rent Price                0
Average Cost of Living             0
Last Data Update                   0
dtype: int64

In [19]:
data[data['Unemployment Rate'].isna()]

,Population Density,Population,Working Age Population,Youth Dependency Ratio,Unemployment Rate,GDP per Capita,Days of very strong heat stress,Main Spoken Languages,Average Monthly Salary,Avgerage Rent Price,Average Cost of Living,Last Data Update
City,,,,,,,,,,,,
"Gent, Belgium",552.0,645813,417832.0,24.8,NaN,53311.0,2,"Dutch, French",2400,827,1200,2023-07-17 00:00:00

In [20]:
data.loc[data.index.str.contains('Belgium')]

,Population Density,Population,Working Age Population,Youth Dependency Ratio,Unemployment Rate,GDP per Capita,Days of very strong heat stress,Main Spoken Languages,Average Monthly Salary,Avgerage Rent Price,Average Cost of Living,Last Data Update
City,,,,,,,,,,,,
"Brussels, Belgium",681.0,3284548,2137425.0,27.50,10.7,62500.0,3,"French, Dutch, Arabic, English",3350,1200,1900,2023-04-22 00:00:00
"Antwerp, Belgium",928.0,1139663,723396.0,27.70,6.2,57595.0,3,"Dutch, French, Arabic",2609,900,1953,2024-08-09 00:00:00
"Gent, Belgium",552.0,645813,417832.0,24.80,NaN,53311.0,2,"Dutch, French",2400,827,1200,2023-07-17 00:00:00
"Bruges, Belgium",840.0,119765,74600.0,25.63,5.6,63083.0,0,"Dutch, French",2700,1250,1708,2023-10-25 00:00:00

In [21]:
data.loc[data.index.str.contains('Belgium'), ['Unemployment Rate']].median()

Unemployment Rate    6.2
dtype: float64

In [22]:
data.loc['Gent, Belgium', ['Unemployment Rate']] =  data.loc[data.index.str.contains('Belgium'), ['Unemployment Rate']].median()

In [23]:
data.isna().sum()

Population Density                 0
Population                         0
Working Age Population             0
Youth Dependency Ratio             0
Unemployment Rate                  0
GDP per Capita                     1
Days of very strong heat stress    0
Main Spoken Languages              0
Average Monthly Salary             0
Avgerage Rent Price                0
Average Cost of Living             0
Last Data Update                   0
dtype: int64

In [24]:
data[data['GDP per Capita'].isna()]

,Population Density,Population,Working Age Population,Youth Dependency Ratio,Unemployment Rate,GDP per Capita,Days of very strong heat stress,Main Spoken Languages,Average Monthly Salary,Avgerage Rent Price,Average Cost of Living,Last Data Update
City,,,,,,,,,,,,
Lemesos;Cyprus,190.0,262238,173906.0,23.06,11.2,NaN,0,"Greek, English, Russian",2500,1400,2300,2023-08-14 00:00:00

In [25]:
data.loc[data.index.str.contains('Cyprus')]

,Population Density,Population,Working Age Population,Youth Dependency Ratio,Unemployment Rate,GDP per Capita,Days of very strong heat stress,Main Spoken Languages,Average Monthly Salary,Avgerage Rent Price,Average Cost of Living,Last Data Update
City,,,,,,,,,,,,
"Lefkosia, Cyprus",130.0,356400,237000.0,23.06,9.6,34907.0,45,"Greek, Turkish, English",1486,700,1350,2024-04-08 00:00:00
Lemesos;Cyprus,190.0,262238,173906.0,23.06,11.2,NaN,0,"Greek, English, Russian",2500,1400,2300,2023-08-14 00:00:00

In [26]:
data.loc[data.index.str.contains('Cyprus'), ['GDP per Capita']].mean()

GDP per Capita    34907.0
dtype: float64

In [27]:
data.loc['Lemesos;Cyprus', ['GDP per Capita']] =  data.loc[data.index.str.contains('Cyprus'), ['GDP per Capita']].median()

In [28]:
data.loc[['Lemesos;Cyprus'], ['GDP per Capita']]

                GDP per Capita
City
Lemesos;Cyprus         34907.0

In [29]:
data.isna().sum()

Population Density                 0
Population                         0
Working Age Population             0
Youth Dependency Ratio             0
Unemployment Rate                  0
GDP per Capita                     0
Days of very strong heat stress    0
Main Spoken Languages              0
Average Monthly Salary             0
Avgerage Rent Price                0
Average Cost of Living             0
Last Data Update                   0
dtype: int64

In [30]:
data[data.duplicated()==True]

,Population Density,Population,Working Age Population,Youth Dependency Ratio,Unemployment Rate,GDP per Capita,Days of very strong heat stress,Main Spoken Languages,Average Monthly Salary,Avgerage Rent Price,Average Cost of Living,Last Data Update
City,,,,,,,,,,,,
Berlin. Germany,304.0,5303922,3481212.0,21.3,4.7,46548.0,3,"German, Turkish, Arabic, English",3200,1220,2200,2023-06-29 00:00:00
"Malaga, Spain",571.0,869096,585608.0,23.5,17.7,27694.0,0,"Spanish, English",2200,1312,1400,2023-11-27 00:00:00

In [31]:
data.drop_duplicates(inplace = True)

In [32]:
split_index = data.index.to_series().apply(
    lambda s: re.split(r'[,;.\-_/]+', s.strip())  # split on any separator
)

# --- 2️⃣ Rejoin all but the last part as "city" ---
split_index = pd.DataFrame(split_index)
split_index.columns = ['parts']
split_index['parts'] = split_index['parts'].apply(lambda lst: [x.strip() for x in lst if x.strip()])

split_index['Country'] = split_index['parts'].apply(lambda lst: lst[-1] if len(lst) > 1 else None)
split_index['City'] = split_index['parts'].apply(lambda lst: ' '.join(lst[:-1]) if len(lst) > 1 else lst[0])

# --- 3️⃣ Fix reversed entries (where the first token looks like a country) ---
# Build a probable country set (based on repetition)
country_counts = split_index['Country'].value_counts()
probable_countries = set(country_counts[country_counts > 1].index)

split_index['Country'], split_index['City'] = zip(*split_index.apply(
    lambda row: (
        row['Country'], row['City']
    ) if row['Country'] in probable_countries or row['Country'] is None else (
        row['City'], row['Country']
    ), axis=1
))

# --- 4️⃣ Create MultiIndex ---
data.index = pd.MultiIndex.from_frame(split_index[['Country', 'City']], names=['Country', 'City'])
data.sort_index(inplace=True)

display(data)

                          Population Density  Population  \
Country        City
Austria        Salzburg                243.0      375489
               Vienna                  310.0     2983513
Belgium        Antwerp                 928.0     1139663
               Bruges                  840.0      119765
               Brussels                681.0     3284548
...                                      ...         ...
United Kingdom Edinburgh               527.0      907580
               Glasgow                 548.0     1845020
               Leeds                   517.0     2641062
               Liverpool              1560.0     1544216
               London                 1777.0    12396541

                          Working Age Population   Youth Dependency Ratio  \
Country        City
Austria        Salzburg                  250472.0                   20.30
               Vienna                   2018818.0                   20.10
Belgium        Antwerp                   723396.0                   27.70
               Bruges                     74600.0                   25.63
               Brussels                 2137425.0                   27.50
...                                           ...                     ...
United Kingdom Edinburgh                 614959.0                   23.40
               Glasgow                  1229657.0                   24.20
               Leeds                    1677791.0                   30.00
               Liverpool                 983056.0                   26.80
               London                   8274794.0                   29.10

                          Unemployment Rate  GDP per Capita  \
Country        City
Austria        Salzburg                 3.0         66689.0
               Vienna                  10.2         55770.0
Belgium        Antwerp                  6.2         57595.0
               Bruges                   5.6         63083.0
               Brussels                10.7         62500.0
...                                     ...             ...
United Kingdom Edinburgh                3.7         54002.0
               Glasgow                  4.8         39666.0
               Leeds                    3.5         37990.0
               Liverpool                7.5         33749.0
               London                   6.1         69863.0

                          Days of very strong heat stress  \
Country        City
Austria        Salzburg                                 0
               Vienna                                   3
Belgium        Antwerp                                  3
               Bruges                                   0
               Brussels                                 3
...                                                   ...
United Kingdom Edinburgh                                0
               Glasgow                                  0
               Leeds                                    0
               Liverpool                                0
               London                                   0

                                      Main Spoken Languages  \
Country        City
Austria        Salzburg                              German
               Vienna     German, English, Turkish, Serbian
Belgium        Antwerp                Dutch, French, Arabic
               Bruges                         Dutch, French
               Brussels      French, Dutch, Arabic, English
...                                                     ...
United Kingdom Edinburgh              English, Scots Gaelic
               Glasgow                       English, Scots
               Leeds                          English, Urdu
               Liverpool                            English
               London        English, Urdu, Bengali, Polish

                          Average Monthly Salary  Avgerage Rent Price  \
Country        City
Austria        Salzburg                     3200                 1100
               Vienna                       2500                 1050
Belgium        Antwerp                      2609                  900
               Bruges                       2700                 1250
               Brussels                     3350                 1200
...                                          ...                  ...
United Kingdom Edinburgh                    2500                 1010
               Glasgow                      2300                 1050
               Leeds                        2300                 1000
               Liverpool                    2250                  950
               London                       2750                 1900

                          Average Cost of Living     Last Data Update
Country        City
Austria        Salzburg                     2186  2023-11-03 00:00:00
               Vienna                       2061  2024-06-15 00:00:00
Belgium        Antwerp                      1953  2024-08-09 00:00:00
               Bruges                       1708  2023-10-25 00:00:00
               Brussels                     1900  2023-04-22 00:00:00
...                                          ...                  ...
United Kingdom Edinburgh                    2050  2023-08-15 00:00:00
               Glasgow                      1950  2023-05-28 00:00:00
               Leeds                        2000  2024-11-03 00:00:00
               Liverpool                    1800  2024-01-23 00:00:00
               London                       2800  2023-04-09 00:00:00

[84 rows x 12 columns]

In [33]:
data.groupby(level = 'Country').size()

Country
Austria            2
Belgium            4
Bratislava         1
Bulgaria           2
Croatia            2
Cyprus             2
Czechia            2
Denmark            2
Finland            2
France             3
Germany           10
Giroc              1
Greece             1
Hungary            3
Ireland            2
Italy              6
Ljubljana          1
Luxembourg         1
Malta              1
Netherlands        5
Norway             3
Poland             3
Portugal           4
Riga               1
Spain              5
Sweden             3
Switzerland        3
Tallinn            1
Thessaloniki       1
Turkiye            2
United Kingdom     5
dtype: int64

In [34]:
display(len(data.index.get_level_values('City')))

84